### PR TITLE
Add GPML2013a-fuller schema, with version of BioPAX as used in GPML2013a

### PR DESCRIPTION
**Pull request by ariutta**
I made a few changes so that XSD processors can handle actual GPML2013a, which has its own version of BioPAX that differs from the BioPAX Level 3 spec.

### CODE REVIEW

**Comment by egonw** [comment]
XML Namespaces FTW :)

**Comment by ariutta** [comment]
I didn't merge this pull request myself, because I want to give time for feedback on this update (pinging @mkutmon and @AlexanderPico). This is still GPML2013a: the update just makes the XSD more closely reflect our actual GPML2013a GPML.

**Comment by AlexanderPico** [comment]
I only see one real difference: removing processContents="skip" from here:
https://github.com/PathVisio/GPML/pull/13/files#diff-36fb8619457b831815471a4174808d12R569

What are the consequences of that change?

The rest is... stuff that... hmm. I'm not going to even bother guessing :)  When is this GPML2013a-biopax.xsd used in practice? Does this affect anyone using it today?

**Comment by ariutta** [comment]
I'm using it to provide types and autocompletion in my code editor.

**Comment by mkutmon** [comment]
Hi Anders! Maybe we should have a short hangout about this and the possible
requirements for the 2017 version I am working on with my GSoC student.

**Comment by ariutta** [comment]
Hi Tina! Sure, we can have a hangout. I can meet anytime this week at 10 or 11am SF time (I think that's 7 or 8pm Maastricht time?). Just let me know.

By the way, this change is not for GPML2017. It's still for GPML2013a. Are you aware of any existing tools that rely on this XSD file? Does PathVisio-Java need to be tested with this updated version?

**Comment by mkutmon** [comment]
Okay great. I'll check my agenda and let you know which day works.
PathVisio definitely needs to be checked since it has the xsd files in the
code.

**Comment by ariutta** [comment]
I added a new schema `GPML2013a-fuller` that I needed in order to use a certain 3rd-party library. There's no need for any of our tooling to change, because the `GPML2013a` schema is unchanged.

**Comment by ariutta** [comment]
I split up this pull request into two separate pull requests: [23](https://github.com/PathVisio/GPML/pull/23) and [24](https://github.com/PathVisio/GPML/pull/24).

**Pull request closed without merging**
